server:
  port: 8082

spring:
  application:
    name: data-collection
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  cloud:
    openfeign:
      okhttp:
        enabled: true
    nacos:
      discovery:
        server-addr: 192.168.86.121:8848

plc_client:
  ip: 127.0.0.1
  port: 8888

conveyor:
  socketio:
    host: 127.0.0.1
    port: 9000
    origin: "*"
    bossCount: 1
    allowCustomRequests: true
