server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 192.168.86.121:8848
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowCredentials: true
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
        add-to-simple-url-handler-mapping: true
      routes:
        - id: front-service
          uri: lb://front-service
          predicates:
            - Path=/user/**,/params/**
        - id: data-collection
          uri: lb://data-collection
          predicates:
            - Path=/control/**

conveyor:
  jwt:
    secretKey: CUMT_B405_DigitalTwigs_Conveyor
    tokenHeader: Authorization
    tokenHead: Bearer
    expiration: 108000000   # 60 * 60 * 3 *1000
  auth:
    excludePaths:
      - /params/get
      - /user/login
      - /user/hi
