server:
  port: 8081

conveyor:
  jwt:
    secretKey: CUMT_B405_DigitalTwigs_Conveyor
    tokenHeader: Authorization
    tokenHead: Bearer
    expiration: 108000000   # 60 * 60 * 3 *1000
  nacos_addr: 192.168.86.121:8848

