server:
  port: 8081
spring:
  application:
    name: data-provider
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  cloud:
    nacos:
      server-addr: 192.168.86.121:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/conveyor_belt?useSSL=FALSE&serverTimezone=UTC
    username: unity
    password: 123456